# Generated by Django 5.1.4 on 2025-10-24 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomenclatura_default",
                    models.CharField(
                        default="INV-",
                        help_text="Prefijo para los códigos de inventario. Ej: INV-",
                        max_length=50,
                        verbose_name="Nomenclatura por Defecto",
                    ),
                ),
                (
                    "ultimo_numero",
                    models.IntegerField(
                        default=0,
                        help_text="Contador para generar códigos únicos",
                        verbose_name="Último Número Generado",
                    ),
                ),
                (
                    "digitos_numeracion",
                    models.IntegerField(
                        default=4,
                        help_text="Número de dígitos para la parte numérica. Ej: 4 = 0001, 0002...",
                        verbose_name="Dígitos de Numeración",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sistema",
                "verbose_name_plural": "Configuración del Sistema",
            },
        ),
        migrations.CreateModel(
            name="TipoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Inventario",
                "verbose_name_plural": "Tipos de Inventario",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("aula", "Aula"),
                            ("armario", "Armario"),
                            ("almacen", "Almacén"),
                            ("oficina", "Oficina"),
                            ("laboratorio", "Laboratorio"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "edificio",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Edificio"
                    ),
                ),
                (
                    "planta",
                    models.CharField(blank=True, max_length=50, verbose_name="Planta"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
                "ordering": ["edificio", "planta", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_inventario",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Código de Inventario",
                    ),
                ),
                (
                    "estado_ficha",
                    models.CharField(
                        choices=[
                            ("vacia", "Ficha Vacía"),
                            ("completada", "Ficha Completada"),
                        ],
                        default="vacia",
                        max_length=20,
                        verbose_name="Estado de Ficha",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "fecha_compra",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Compra"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_uso", "En Uso"),
                            ("mantenimiento", "Mantenimiento"),
                            ("baja", "Dado de Baja"),
                            ("extraviado", "Extraviado"),
                        ],
                        default="disponible",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "campo_libre_1",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Campo Libre 1"
                    ),
                ),
                (
                    "campo_libre_2",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Campo Libre 2"
                    ),
                ),
                (
                    "campo_libre_3",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Campo Libre 3"
                    ),
                ),
                (
                    "campo_libre_4",
                    models.TextField(blank=True, verbose_name="Campo Libre 4"),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, upload_to="qr_codes/", verbose_name="Código QR"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventarios_completados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Completado por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventarios_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "tipo_inventario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventarios",
                        to="inventory_app.tipoinventario",
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventarios",
                        to="inventory_app.ubicacion",
                        verbose_name="Ubicación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario",
                "verbose_name_plural": "Inventarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistorialInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=50, verbose_name="Acción")),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="inventory_app.inventario",
                        verbose_name="Inventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Inventario",
                "verbose_name_plural": "Historiales de Inventario",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="FotoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        upload_to="inventario_fotos/", verbose_name="Fotografía"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                (
                    "es_principal",
                    models.BooleanField(default=False, verbose_name="Foto Principal"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="inventory_app.inventario",
                        verbose_name="Inventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotografía de Inventario",
                "verbose_name_plural": "Fotografías de Inventario",
                "ordering": ["-es_principal", "-created_at"],
            },
        ),
    ]
