# Generated by Django 5.1.4 on 2025-10-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionsistema",
            name="etiquetas_por_columna",
            field=models.IntegerField(
                default=2,
                help_text="Número de etiquetas verticales en el PDF",
                verbose_name="Etiquetas por Columna",
            ),
        ),
        migrations.AddField(
            model_name="configuracionsistema",
            name="etiquetas_por_fila",
            field=models.IntegerField(
                default=2,
                help_text="Número de etiquetas horizontales en el PDF",
                verbose_name="Etiquetas por Fila",
            ),
        ),
    ]
